const interior = [
    {
        image:'/interior/int1.jpg'
    },
    {
        image:'/interior/int2.jpg'
    },
    {
        image:'/interior/int3.jpg'
    },
    {
        image:'/interior/int4.jpg'
    },
    {
        image:'/interior/int5.jpg'
    },
    {
        image:'/interior/int6.jpg'
    },
    {
        image:'/interior/int7.jpg'
    },
    {
        image:'/interior/int8.jpg'
    },
    {
        image:'/interior/int9.jpg'
    },
    {
        image:'/interior/int10.jpg'
    },
    {
        image:'/interior/int11.jpg'
    },
    {
        image:'/interior/int12.jpg'
    },
    {
        image:'/interior/int13.jpg'
    },
    {
        image:'/interior/int14.jpg'
    },
    {
        image:'/interior/int15.jpg'
    },
    {
        image:'/interior/int16.jpg'
    },
    {
        image:'/interior/int17.jpg'
    },
    {
        image:'/interior/int18.jpg'
    },
    {
        image:'/interior/int19.jpg'
    },
    {
        image:'/interior/int20.jpg'
    }
]
module.exports = interior;